### ISSUE TITLE
Стал зависать просмотр личных сертификатов

### ISSUE THREAD

**Issue by x09** [bmakarenko/token-manager#10]
С некоторых пор, стал висеть бесконечно, раньше работало.
Когда нажимаю ctrl-C выкидывает

```
Traceback (most recent call last):
  File "/usr/bin/token-manager.py", line 991, in select_token
    certs = get_store_certs(item.storage)
  File "/usr/bin/token-manager.py", line 278, in get_store_certs
    m = re.findall(r'(\d+)-{7}\nIssuer.*?: (.+?)\n.*?Subject.*?: (.+?)\n.*?Serial.*?: (0x\w+?)\nSHA1 Hash.*?(\w+?)\n.*?Not valid before.*?(\d.+?)UTC\nNot valid after.*?(\d.+?)UTC.+?Extended Key Usage.*?([\d\.\s]+)\n', output, re.MULTILINE + re.DOTALL)
  File "/usr/lib64/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
KeyboardInterrupt
^C^CTraceback (most recent call last):
  File "/usr/bin/token-manager.py", line 1128, in <module>
    main()
  File "/usr/bin/token-manager.py", line 1121, in main
    sys.exit(app.exec_())
```
сам криптопро вполне работает  /opt/cprocsp/bin/amd64/certmgr -list

**Comment by bmakarenko** [comment]
Можно вывод /opt/cprocsp/bin/amd64/certmgr -list
Возможно что-то с регэкспом

**Comment by x09** [comment]
Немного пояснений.
Хранилище корневых - показывает отлично.
С картридера - отлично.
А вот личное хранилище сертификатов - зависает насмерть. Только xkill помогает.

В консоли /opt/cprocsp/bin/amd64/certmgr -list успешно отрабатывает ErrorCode: 0x0000000
Показывает все сертификаты.. Может, мой новый, который ГОСТ 2012 мешает ему? Раньше, когда его не было - все было ок вроде.

![1](https://user-images.githubusercontent.com/1303927/54970918-f6c7d400-4fa5-11e9-8b9b-09607640893d.jpg)

**Comment by bmakarenko** [comment]
У вас корневые сертификаты в личном хранилище. Они там не нужны. Удалите и все будет ок

**Comment by x09** [comment]
удалить то можно, но это же ошибка, не? )

**Comment by bmakarenko** [comment]
Согласен. Просто сложно это одним регэкспом отследить. Ничего не обещаю, постараюсь сделать. А пока не устанавливайте корневые сертификаты в uMy. Смысла в этом нет, а программа глючит.
