### ISSUE TITLE
Ошибка в Операции > Просмотр корневых сертификатов

### ISSUE THREAD

**Issue by TurboBlaze** [bmakarenko/token-manager#7]
Если зайти в Операции > Просмотр корневых сертификатов, то в терминале возникает такая ошибка:

```
Traceback (most recent call last):
  File "/usr/bin/token-manager.py", line 821, in view_root
    root_view = ListCert(root_info, True)
  File "/usr/bin/token-manager.py", line 693, in __init__
    self.filterout()
  File "/usr/bin/token-manager.py", line 702, in filterout
    not_valid_before = datetime.strptime(line[5], '%d/%m/%Y  %H:%M:%S ')
  File "/usr/lib64/python2.7/_strptime.py", line 14, in <module>
    import locale
  File "/usr/lib64/python2.7/locale.py", line 18, in <module>
    import operator
ImportError: /usr/lib64/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString
```

**Comment by bmakarenko** [comment]
Возникает ли такая-же ошибка при просмотре списков отозванных сертификатов? Если да, то у вас что-то не так с модулем operator. Ошибка на простой операции - форматирование даты/времени даты выдачи корневого сертификата.
